theme: jekyll-theme-minimal
title: Devon Sampson and Polyculture Research & Media
logo: "/images/bio.jpeg"
description: Welcome! I'm working on several data science projects for public health and sustainable food systems applications.
