theme: jekyll-theme-cayman
title: Devon Sampson and Polyculture Research & Media
description: Welcome! I'm working on several data science projects for public health and sustainable food systems applications.
